language: node_js
node_js: 
  - "stable"
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  - "rake db:migrate"
cache:
  directories:
    - "node_modules"