swagger: "2.0"
info:
  title: Teamwork Backend API
  description: API description in Markdown for Teamwork Backend Application.
  version: 1.0.0
host: localhost
basePath: /api/v1
schemes:
  - https
  - http
paths:
  /auth/login:
    post:
      summary: Login.
      description: Login Admin/Employee.
      produces:
        - application/json
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/Login"
      responses:
        200:
          description: "login successfully with token"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"
  /employees:
    get:
      security:
        - Bearer: []
      summary: Get all employees.
      description: This route only works for admin.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /auth/createuser:
    post:
      security:
        - Bearer: []
      summary: Create User.
      description: This route only works for admin.
      produces:
        - application/json
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "login successfully with token"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid data supplied"
  /users:
    get:
      security:
        - Bearer: []
      summary: Get all users for employees.
      description: This route only works for employees.
      produces:
        - application/json
      responses:
        200:
          description: OK
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Login:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
    xml:
      name: "Login"
  User:
    type: "object"
    properties:
      fullname:
        type: "string"
      phone:
        type: "string"
      jobrole:
        type: "string"
      address:
        type: "string"
      gender:
        type: "string"
      department:
        type: "string"
      email:
        type: "string"
    xml:
      name: "User"